# Generated by Django 4.0.4 on 2022-05-10 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animal_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animallist',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_list', to='animal_app.animals'),
        ),
    ]
